[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["npm ci --omit=dev"]

# Skip build phase since this is a server, not a React app
[phases.build]
cmds = []

[phases.start]
cmd = "npm start"